# Generated by Django 4.2.3 on 2023-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aircraft_user_alter_operator_caa_code_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('question', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='operator',
            name='caa_code',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='CAA Code'),
        ),
    ]
