# Generated by Django 4.2.3 on 2023-07-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_aircraft_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='operator',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
