# Generated by Django 4.2.3 on 2023-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_operator_file1_operator_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='static/certificates/', verbose_name='Certificat A1/A3'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='static/certificates/', verbose_name='Certificat A2'),
        ),
    ]
